image: homeassistant/{arch}-base
shadow_repository: ghcr.io/home-assistant
build_from:
  aarch64: "arm64v8/alpine:3.16"
  armv7: "arm32v7/alpine:3.16"
  armhf: "arm32v6/alpine:3.16"
  amd64: "alpine:3.16"
  i386: "i386/alpine:3.16"
codenotary:
  signer: jim@jimdrury.co.uk
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.2.1
  JEMALLOC_VERSION: 5.3.0
labels:
  io.hass.base.name: alpine
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
