name: "Hoover Dryer"
description: "This will allow Hoover Dryer devices to be discovered and controlled."

version: "0.0.18"

slug: "hoover_dryer"

init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  mqtt_host: "homeassistant.local"
  mqtt_port: "1883"

schema:
  mqtt_host: str
  mqtt_port: str
  mqtt_username: str
  mqtt_password: password

image: jimdrury/{arch}-homeassistant-hoover-dryer

host_network: true

discovery:
  - mqtt
