name: "Hoover Dryer"
description: "This will allow Hoover Dryer devices to be discovered and controlled."

version: "0.0.42"

slug: "hoover_dryer"

init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

image: jimdrury/{arch}-homeassistant-hoover-dryer

map:
  - share:rw

host_network: true

discovery:
  - mqtt

services:
  - mqtt:need
