name: "Test"

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: 'hoover-dryer'

      - name: Build Dist
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
          dir: 'hoover-dryer'

      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target hoover-dryer \
            --docker-hub jimdrury
