name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: 'hoover-dryer'

      - name: Build Dist
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
          dir: 'hoover-dryer'

      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target hoover-dryer \
            --docker-hub jimdrury
